### ISSUE TITLE
Extension project failed to build

### ISSUE THREAD

**Issue by ingted** [dotnet-websharper/core#1125]
```
dotnet new websharper-ext -n extTest
```
And then build with VS2019 Preview 16.10.0 Preview 1.0
with environments:

OS: Windows Server 2019
SDKs:
```
dotnet --list-sdks
3.1.200 [C:\Program Files\dotnet\sdk]
3.1.201 [C:\Program Files\dotnet\sdk]
3.1.300-preview-015115 [C:\Program Files\dotnet\sdk]
3.1.300 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]
5.0.104 [C:\Program Files\dotnet\sdk]
5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
5.0.201 [C:\Program Files\dotnet\sdk]
```

Repo: [test Websharper Extension](https://github.com/ingted/testWSExt)

Got  FSC error:

```
FSC : WebSharper error FS9001: Error running WIG assembly: System.TypeInitializationException: The type initializer for '<StartupCode$extTest2>.$Main' threw an exception. ---> System.MissingMethodException: Method not found: 'Interface Interface.op_BarPlusGreater(Interface, Microsoft.FSharp.Collections.FSharpList`1<!!0>)'.   at <StartupCode$extTest2>.$Main..cctor()   --- End of inner exception stack trace ---   at extTest2.Definition.get_Assembly()   at extTest2.Extension.WebSharper.InterfaceGenerator.Pervasives.IExtension.get_Assembly()   at WebSharper.Compiler.CommandTools.LoadInterfaceGeneratorAssembly(String file)   at WebSharper.Compiler.CommandTools.RunInterfaceGenerator@334.Invoke(Unit unitVar0)   at WebSharper.Compiler.AssemblyResolver.Wrap[T](FSharpFunc`2 action)   at WebSharper.Compiler.CommandTools.RunInterfaceGenerator(AssemblyResolver aR, FSharpOption`1 snk, WsConfig config)   at WebSharper.FSharp.Program.Compile@104.Invoke(Unit unitVar0)
```

**So far, no workaround...**

**Comment by ingted** [comment]
One workaround is to change targetframework to netstandard2.0...

**Comment by granicz** [comment]
@ingted Out of curiosity, what was your target framework set to before? @Jand42 can you take a look?

**Comment by ingted** [comment]
answer: target framework set to before => 2.0
why I can build with 2.1 was because some operation caused WebSharper.FSharp reference was gone... (so always buildable)

Now I found the workable set is:

![image](https://user-images.githubusercontent.com/4289161/115193897-50684180-a11f-11eb-874c-f51cb0d768e7.png)

**Comment by Jand42** [comment]
@ingted The stable 3.1 SDK is the one guaranteed to work for current WebSharper 4.7.x release, using `global.json`:
```json
{
  "sdk": {
    "version": "3.1.201",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}
```
(I will test and rebase a fix to master from WIP websharper50 branch if it makes it working better with net5.0 or even 6.0-preview)

**Comment by ingted** [comment]
After added global.json
modified targetframework to netcoreapp3.1
and (successfully executed in Powershell)
```
dotnet tool restore
dotnet restore
```

The build still failed...

![image](https://user-images.githubusercontent.com/4289161/115250746-74964380-a15c-11eb-8d44-fe1a24627f18.png)

![image](https://user-images.githubusercontent.com/4289161/115250856-8d065e00-a15c-11eb-9ccf-6f63cb19477d.png)

**Comment by ingted** [comment]
```
FSC : WebSharper error FS9001: Error running WIG assembly: System.Exception: Could not resolve type System.Attribute in netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1639.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1639
   at WebSharper.InterfaceGenerator.TypeBuilder.doResolveTypeName(AssemblyDefinition asm, String typeName)
   at WebSharper.InterfaceGenerator.TypeBuilder.resolveTypeName(AssemblyDefinition asm, String typeName)
   at WebSharper.InterfaceGenerator.TypeBuilder.resolveType(Type ty)
   at WebSharper.InterfaceGenerator.TypeBuilder..ctor(Resolver aR, AssemblyDefinition out, FSharpOption`1 netStandardPath)
   at WebSharper.InterfaceGenerator.Compiler.buildAssembly(Resolver resolver, CompilerOptions options, Assembly assembly)
   at WebSharper.InterfaceGenerator.Compiler.Compile(Resolver resolver, CompilerOptions options, Assembly assembly, FSharpOption`1 originalAssembly)
   at WebSharper.InterfaceGenerator.Compiler.Compile(CompilerOptions options, Assembly assembly, FSharpOption`1 original)
   at WebSharper.Compiler.CommandTools.RunInterfaceGenerator@334.Invoke(Unit unitVar0)
   at WebSharper.Compiler.AssemblyResolver.Wrap[T](FSharpFunc`2 action)
   at WebSharper.Compiler.CommandTools.RunInterfaceGenerator(AssemblyResolver aR, FSharpOption`1 snk, WsConfig config)
   at WebSharper.FSharp.Program.Compile@104.Invoke(Unit unitVar0)
```

**Comment by Jand42** [comment]
@ingted related fixes released in https://github.com/dotnet-websharper/core/releases/tag/4.7.1.432
VS2019Preview is still not fully supported, I will wait for stable. Also on Extension/InterfaceGenerator projects, you need an FSharp.Core lower than 5.0, I have updated Extension templates for this.
